version: '3.7'
services:
  gift-list:
    build: .
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
    - mysql
    environment:
    - DATABASE_URI=${DATABASE_URI}
    - SECRET_KEY=${SECRET_KEY}
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - type: volume
        source: mysqldata
        target: /var/lib/mysql
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
    - gift-list

volumes:
  mysqldata:
